# -----------------------------
# Server Settings
# -----------------------------
server.port=8080

# -----------------------------
# PostgreSQL Database Settings
# -----------------------------
spring.datasource.url=jdbc:postgresql://localhost:5433/habitdb
spring.datasource.username=postgres
spring.datasource.password=1234

# -----------------------------
# Hibernate / JPA Settings
# -----------------------------
# Automatically update schema based on entities
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in console (good for learning)
spring.jpa.show-sql=true

# Format SQL output
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.session.jdbc.initialize-schema=always
